### ISSUE TITLE
Twilio Error - 11200 :: 

### ISSUE THREAD

**Issue by celamb4** [cognitive-catalyst/twilio#4]
This is a great tutorial. However, I tried to implement and my bluemix app is not allowing twilio to post the information. Not sure if the readme is missing a step? It would be great to provide some pointers to enable bluemix messages api to accept twilio posts.

HTTP RESPONSE:
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by amchaney** [comment]
As it turns out, there is a dependency we did not explicitly call out in the instructions.  When you enable the add-ons you can configure a name for the add-on message.  This code assumes that you named the message insights `ibm_watson_insights` and the sentiment add on `ibm_watson_sentiment` 
<img width="588" alt="screen shot 2016-11-04 at 3 56 55 pm" src="https://cloud.githubusercontent.com/assets/16139315/20022267/aeb8dde2-a2a7-11e6-9d9f-4cc2325ea92c.png">
<img width="571" alt="screen shot 2016-11-04 at 3 57 06 pm" src="https://cloud.githubusercontent.com/assets/16139315/20022280/b39460e8-a2a7-11e6-8535-2033566776c3.png">
problem for @celamb4 has been resolved.
